export enum FormInput {
  EMAIL = 'email',
  NAME = 'name',
  USERNAME = 'username',
  PASSWORD = 'password',
  CONFIRM_PASSWORD = 'confirmPassword',
  FILE = 'file',
  TEXT = 'text',
  TYPE = 'type',
  QUESTIONS = 'questions',
  PUBLISHED = 'published',
  TITLE = 'title',
  DESCRIPTION = 'description',
  CATEGORIES = 'categories',
  QUESTION = 'question',
  OPTIONS = 'options',
  OPTION = 'option',
  CORRECT_OPTIONS = 'correctOptions',
  ANSWERED_QUESTIONS = 'answeredQuestions',
  SEARCH = 'search'
}
